### ISSUE TITLE
some papers to add

### ISSUE THREAD

**Issue by fawazsammani** [tomohideshibata/BERT-related-papers#22]
For Multi-Modal section:

[VinVL: Revisiting Visual Representations in Vision-Language Models](https://arxiv.org/abs/2101.00529)
[12-in-1: Multi-Task Vision and Language Representation Learning](https://arxiv.org/abs/1912.02315)
[ViLT: Vision-and-Language Transformer Without Convolution or Region Supervision](https://arxiv.org/abs/2102.03334)
[XGPT: Cross-modal Generative Pre-Training for Image Captioning](https://arxiv.org/abs/2003.01473)
[InterBERT: Vision-and-Language Interaction for Multi-modal Pretraining](https://arxiv.org/abs/2003.13198)

And for Downstream task section: 

[CAPT: Contrastive Pre-Training for Learning Denoised Sequence Representations](https://arxiv.org/abs/2010.06351)

**Comment by tomohideshibata** [comment]
Thanks! I have added these papers via https://github.com/tomohideshibata/BERT-related-papers/commit/256983d21d559095df93cf46d53832f844d2b044 and https://github.com/tomohideshibata/BERT-related-papers/commit/8a4e7013dc568f5663f9b053c929b6ec08d3388a.
