### ISSUE TITLE
some papers to add

### ISSUE THREAD

**Issue by fawazsammani** [tomohideshibata/BERT-related-papers#30]
Inside BERT:
- Behind the Scene: Revealing the Secrets of Pre-trained Vision-and-Language Models: https://arxiv.org/pdf/2005.07310.pdf
- A Closer Look at the Robustness of Vision-and-Language Pre-trained Models: https://arxiv.org/pdf/2012.08673.pdf

Model Compression:
- Contrastive Distillation on Intermediate Representations for Language Model Compression: https://arxiv.org/pdf/2009.14167.pdf
- MiniVLM: A Smaller and Faster Vision-Language Model: https://arxiv.org/pdf/2012.06946.pdf
- Compressing Visual-linguistic Model via Knowledge Distillation: https://arxiv.org/pdf/2104.02096.pdf

Multi-Modal
- Large-Scale Adversarial Training for Vision-and-Language Representation Learning: https://arxiv.org/pdf/2006.06195.pdf
- UNIMO: Towards Unified-Modal Understanding and Generation via Cross-Modal Contrastive Learning: https://arxiv.org/pdf/2012.15409.pdf
- Seeing Out of tHe bOx: End-to-End Pre-training for Vision-Language Representation Learning: https://arxiv.org/pdf/2104.03135.pdf
- Contrastive Visual-Linguistic Pretraining: https://arxiv.org/pdf/2007.13135.pdf
- TAP: Text-Aware Pre-training for Text-VQA and Text-Caption: https://arxiv.org/pdf/2012.04638.pdf

**Comment by tomohideshibata** [comment]
Thanks! I will add these papers soon.

**Comment by tomohideshibata** [comment]
I added these papers via https://github.com/tomohideshibata/BERT-related-papers/commit/6febe6e202d800ac668ce9533ba8c3c2bd8aacd7, https://github.com/tomohideshibata/BERT-related-papers/commit/003ffb62c44a07508030d618b5eebd04a20dc568 and https://github.com/tomohideshibata/BERT-related-papers/commit/34d9317431ed96a5a000f12d0fbcfc3c549ab569.
(The paper "A Closer Look at the Robustness of Vision-and-Language Pre-trained Models" has been already added.)
