### ISSUE TITLE
Please add a new ACL2022 probing paper: https://aclanthology.org/2022.acl-long.75/

### ISSUE THREAD

**Issue by flyaway1217** [tomohideshibata/BERT-related-papers#40]
Please add a new ACL2022 probing paper: https://aclanthology.org/2022.acl-long.75/
Thanks!

**Comment by tomohideshibata** [comment]
Thanks! I have added this paper via https://github.com/tomohideshibata/BERT-related-papers/commit/9818fbaa476ffae07a863ecb70b74930046b3f47 .
